FROM ghcr.io/juanfont/headscale:0.25 AS headscale-bin

FROM alpine:3.21
COPY --from=headscale-bin /ko-app/headscale /usr/local/bin/headscale
RUN apk add --no-cache bash
COPY tests/e2e/headscale-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

CMD ["/entrypoint.sh"]
