"""Integration tests: IPsec/IKEv2 connect/disconnect with real strongSwan server.

Runs inside privileged container. strongSwan server must be running in vpn-e2e network.
Client config is generated by the server and shared via volume at /shared/ipsec/ipsec-client.conf.
"""

from __future__ import annotations

import subprocess
import time
from pathlib import Path

import pytest


pytestmark = pytest.mark.network


def _restart_charon() -> bool:
    """(Re)start charon daemon. Returns True if VICI socket is available."""
    import shutil

    # Stop any existing charon (systemd or standalone)
    if shutil.which("systemctl"):
        subprocess.run(
            ["systemctl", "stop", "strongswan-starter"],
            capture_output=True,
            check=False,
        )
        subprocess.run(
            ["systemctl", "stop", "strongswan"],
            capture_output=True,
            check=False,
        )
    subprocess.run(["ipsec", "stop"], capture_output=True, check=False)
    time.sleep(1)

    # Kill any lingering charon
    subprocess.run(["pkill", "-9", "charon"], capture_output=True, check=False)
    time.sleep(0.5)

    for f in ("/var/run/charon.pid", "/var/run/charon.vici"):
        Path(f).unlink(missing_ok=True)

    subprocess.run(["ipsec", "start"], capture_output=True, check=False)
    for _ in range(20):
        time.sleep(0.5)
        if Path("/var/run/charon.vici").exists():
            return True
    return False


def _swanctl(args: list[str], timeout: int = 10) -> subprocess.CompletedProcess:
    """Run swanctl command and return result."""
    return subprocess.run(
        ["swanctl", *args],
        capture_output=True,
        text=True,
        timeout=timeout,
    )


class TestIPsecConnect:
    """Real IPsec/IKEv2 connection lifecycle via swanctl.

    Uses a single test to avoid charon restart issues between tests.
    Flow: start charon -> load -> initiate -> verify ESTABLISHED -> terminate -> verify gone.
    """

    def test_full_ipsec_lifecycle(self, ipsec_client_config: Path, requires_tun):
        """Full IPsec lifecycle: load, initiate, verify SA, terminate, verify cleanup."""
        # Start fresh charon
        ok = _restart_charon()
        assert ok, "charon VICI socket not available"

        try:
            # 1. Load config
            load = _swanctl(["--load-all", "--file", str(ipsec_client_config)])
            assert load.returncode == 0, f"swanctl --load-all failed: {load.stderr}"

            # 2. Initiate connection
            init = _swanctl(["--initiate", "--child", "test-child"])
            assert init.returncode == 0, f"swanctl --initiate failed: {init.stderr}"

            # 3. Verify SA is ESTABLISHED
            time.sleep(1)
            sas = _swanctl(["--list-sas"])
            assert sas.returncode == 0, f"swanctl --list-sas failed: {sas.stderr}"
            assert "test-vpn" in sas.stdout, (
                f"SA 'test-vpn' not found in:\n{sas.stdout}"
            )
            assert "ESTABLISHED" in sas.stdout, (
                f"Expected ESTABLISHED in SA output:\n{sas.stdout}"
            )

            # 4. Terminate
            term = _swanctl(["--terminate", "--ike", "test-vpn"])
            assert term.returncode == 0, f"swanctl --terminate failed: {term.stderr}"
            time.sleep(1)

            # 5. Verify no active SAs
            sas_after = _swanctl(["--list-sas"])
            assert "ESTABLISHED" not in sas_after.stdout, (
                f"SA still active after terminate:\n{sas_after.stdout}"
            )

        finally:
            # Best-effort cleanup
            _swanctl(["--terminate", "--ike", "test-vpn"])
            subprocess.run(["ipsec", "stop"], capture_output=True, check=False)
