"""Integration tests: WireGuard connect/disconnect with real server.

Runs inside privileged container. WireGuard server must be running in vpn-e2e network.
Client config is generated by the server and shared via volume at /shared/wg/wg-client.conf.
"""

from __future__ import annotations

import subprocess
import time
from pathlib import Path

import pytest

from tv.net import NetManager


pytestmark = pytest.mark.network


def _wait_for_wg_interface(real_net: NetManager, ifaces_before: set, timeout: int = 15):
    """Wait for a new wg/utun interface to appear. Returns interface name or None."""
    for _ in range(timeout * 2):
        time.sleep(0.5)
        ifaces_now = set(real_net.interfaces().keys())
        new = ifaces_now - ifaces_before
        wg_ifaces = [i for i in new if i.startswith(("wg", "utun"))]
        if wg_ifaces:
            return sorted(wg_ifaces)[0]
    return None


class TestWireGuardConnect:
    """Real WireGuard connection lifecycle."""

    def test_connect_creates_interface(
        self, wireguard_client_config: Path, real_net: NetManager, requires_tun
    ):
        """wg-quick up creates a WireGuard interface with correct IP."""
        ifaces_before = set(real_net.interfaces().keys())

        result = subprocess.run(
            ["wg-quick", "up", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )

        try:
            assert result.returncode == 0, f"wg-quick up failed: {result.stderr}"

            new_iface = _wait_for_wg_interface(real_net, ifaces_before)
            assert new_iface is not None, (
                f"No WireGuard interface appeared. Ifaces: {real_net.interfaces()}"
            )

            info = real_net.iface_info(new_iface)
            assert "10.30.0.2" in info, f"Expected 10.30.0.2, got: {info}"

        finally:
            subprocess.run(
                ["wg-quick", "down", str(wireguard_client_config)],
                capture_output=True,
            )

    def test_disconnect_removes_interface(
        self, wireguard_client_config: Path, real_net: NetManager, requires_tun
    ):
        """After wg-quick down, interface disappears."""
        ifaces_before = set(real_net.interfaces().keys())

        up_result = subprocess.run(
            ["wg-quick", "up", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )
        assert up_result.returncode == 0, f"wg-quick up failed: {up_result.stderr}"

        new_iface = _wait_for_wg_interface(real_net, ifaces_before)
        assert new_iface is not None, (
            f"Interface never appeared. Ifaces: {real_net.interfaces()}"
        )

        result = subprocess.run(
            ["wg-quick", "down", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"wg-quick down failed: {result.stderr}"
        time.sleep(1)

        ifaces_after = set(real_net.interfaces().keys())
        leftover = ifaces_after - ifaces_before
        wg_ifaces = [i for i in leftover if i.startswith(("wg", "utun"))]
        assert len(wg_ifaces) == 0, f"Leftover WireGuard interfaces: {wg_ifaces}"

    def test_wg_show_reports_peer(
        self, wireguard_client_config: Path, real_net: NetManager, requires_tun
    ):
        """wg show reports active peer after connect."""
        up_result = subprocess.run(
            ["wg-quick", "up", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )
        assert up_result.returncode == 0, f"wg-quick up failed: {up_result.stderr}"

        try:
            result = subprocess.run(
                ["wg", "show"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            assert result.returncode == 0
            assert (
                "peer:" in result.stdout.lower() or "peer" in result.stdout.lower()
            ), f"No peer in wg show output:\n{result.stdout}"
            assert "endpoint" in result.stdout.lower(), (
                f"No endpoint in wg show output:\n{result.stdout}"
            )

        finally:
            subprocess.run(
                ["wg-quick", "down", str(wireguard_client_config)],
                capture_output=True,
            )

    def test_ping_through_tunnel(
        self, wireguard_client_config: Path, real_net: NetManager, requires_tun
    ):
        """Can ping WireGuard server gateway (10.30.0.1) through tunnel."""
        ifaces_before = set(real_net.interfaces().keys())

        up_result = subprocess.run(
            ["wg-quick", "up", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )
        assert up_result.returncode == 0, f"wg-quick up failed: {up_result.stderr}"

        try:
            new_iface = _wait_for_wg_interface(real_net, ifaces_before)
            assert new_iface is not None, "Interface never appeared"
            time.sleep(1)

            result = subprocess.run(
                ["ping", "-c", "3", "-W", "2", "10.30.0.1"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            assert result.returncode == 0, (
                f"Ping to WireGuard gateway failed:\n{result.stdout}\n{result.stderr}"
            )

        finally:
            subprocess.run(
                ["wg-quick", "down", str(wireguard_client_config)],
                capture_output=True,
            )

    def test_routes_added_for_tunnel_subnet(
        self, wireguard_client_config: Path, real_net: NetManager, requires_tun
    ):
        """wg-quick adds routes for AllowedIPs (10.30.0.0/24)."""
        ifaces_before = set(real_net.interfaces().keys())

        result = subprocess.run(
            ["wg-quick", "up", str(wireguard_client_config)],
            capture_output=True,
            text=True,
        )

        try:
            assert result.returncode == 0, f"wg-quick up failed: {result.stderr}"

            new_iface = _wait_for_wg_interface(real_net, ifaces_before)
            assert new_iface is not None, "Interface never appeared"
            time.sleep(1)

            route_table = real_net.route_table()
            assert "10.30.0" in route_table, (
                f"Expected 10.30.0.0/24 route in table:\n{route_table}"
            )

        finally:
            subprocess.run(
                ["wg-quick", "down", str(wireguard_client_config)],
                capture_output=True,
            )
