FROM alpine:3.21

RUN apk add --no-cache openvpn

COPY k8s/test-vpn/pki/openvpn-ca.crt /etc/openvpn/pki/ca.crt
COPY k8s/test-vpn/pki/openvpn-server.crt /etc/openvpn/pki/server.crt
COPY k8s/test-vpn/pki/openvpn-server.key /etc/openvpn/pki/server.key
COPY k8s/test-vpn/pki/openvpn-dh.pem /etc/openvpn/pki/dh.pem
COPY k8s/test-vpn/pki/openvpn-ta.key /etc/openvpn/ta.key
COPY k8s/test-vpn/pki/client.ovpn /etc/openvpn/client.ovpn
COPY k8s/test-vpn/openvpn-server.conf /etc/openvpn/server.conf

CMD ["sh", "-c", "mkdir -p /dev/net && [ -c /dev/net/tun ] || mknod /dev/net/tun c 10 200 && exec openvpn --config /etc/openvpn/server.conf"]
